# Generated by Django 2.2 on 2022-07-23 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20220723_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleentry',
            name='id',
        ),
        migrations.AlterField(
            model_name='articleentry',
            name='topic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='articles.ArticleTopic'),
        ),
    ]
