# Generated by Django 2.2 on 2022-07-23 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20220723_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletopic',
            name='text',
            field=models.CharField(blank=True, max_length=40, unique=True),
        ),
    ]
